#!/bin/bash

ssh -t $1 '
  sudo apt-get update
  apt-get upgrade -y --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
  curl -L https://www.opscode.com/chef/install.sh | sudo bash
'
